project:
  type: website
  output-dir: 'docs'

website:
  title: "netdiffuseR: A workshop"
  # body-footer: <text style="text-align:center">ForeSITE</text>
  repo-url: https://github.com/USCCANA/netdiffuser-workshop
  repo-actions: [edit, source]
  navbar:
    left:
    - text: Home
      href: index.qmd
    - text: Lectures
      menu:
      - text: Getting Started
        href: 0-getstarted.qmd
      - text: Diffusion Theory
        href: 1-theory.qmd
      - text: The netdiffuseR package
        href: 2-netdiffuser.qmd
      - text: Simulations
        href: 3-sim.qmd
      - text: New features
        href: 4-newfeatures.qmd
      - text: Reading data
        href: 5-read.qmd
      - text: Statistical inference
        href: 6-stats.qmd
    - text: Classic Diffnet Analyses
      href: classic.qmd

format:
  html:
    theme: cosmo
    toc: true

execute: 
  freeze: auto

