project:
  type: website
  output-dir: 'docs'

website:
  title: "netdiffuseR: A workshop"
  # body-footer: <text style="text-align:center">ForeSITE</text>
  repo-url: https://github.com/USCCANA/netdiffuser-workshop
  repo-actions: [edit, source]
  navbar:
    left:
    - text: Home
      href: index.qmd
    - text: Lectures
      menu:
      - text: Diffusion Theory
        href: 1-theory.qmd
      - text: Reading data
        href: 2-read.qmd
      - text: Visualization
        href: 3-visualization.qmd
      - text: Statistical Analysis
        href: 4-stats.qmd
      - text: Simulations pt.1
        href: 5-sim.qmd
      - text: Simulations pt.2
        href: 6-multi-and-dis.qmd
    - text: Miscellaneous
      menu:
      - text: Getting started with R
        href: 0-getstarted.qmd
      - text: Classic Diffnet Analyses
        href: classic.qmd

format:
  html:
    theme: cosmo
    toc: true

execute: 
  freeze: auto

