---
title: "netdiffuseR workshop"
author:
  - George G. Vega Yon
  - Anibal L. Olivera M.
  - Thomas W. Valente 
---

```{r setup, echo=FALSE}
knitr::opts_chunk$set(comment = "#")
```


Workshop materials can be downloaded from https://github.com/USCCANA/netdiffuser-sunbelt2018/tree/sunbelt2019. You can download the entire repository (source code of the workshop) [here](https://github.com/USCCANA/netdiffuser-sunbelt2018/archive/sunbelt2019.zip).

Source code per section:

1.  <a href="Network Interventions INSNA updated.ppt" target="_blank">Presentation</a>
2.  <a href="https://raw.githubusercontent.com/USCCANA/netdiffuser-sunbelt2018/sunbelt2019/getstarted.Rmd" target="_blank">Getting started</a>
3.  <a href="https://raw.githubusercontent.com/USCCANA/netdiffuser-sunbelt2018/sunbelt2019/intro.Rmd" target="_blank">Introduction</a>
4.  <a href="https://raw.githubusercontent.com/USCCANA/netdiffuser-sunbelt2018/sunbelt2019/sim.Rmd" target="_blank">Simulations</a>
5.  <a href="https://raw.githubusercontent.com/USCCANA/netdiffuser-sunbelt2018/sunbelt2019/stats.Rmd" target="_blank">Statistical inference</a>
5.  <a href="https://raw.githubusercontent.com/USCCANA/netdiffuser-sunbelt2018/sunbelt2019/classic.Rmd" target="_blank">Classic Diffnet Analyses</a>

From the description:

> Empirical statistical analysis, visualization and simulation of diffusion and contagion processes on networks. The package implements algorithms for calculating network diffusion statistics such as transmission rate, hazard rates, exposure models, network threshold levels, infectiousness (contagion), and susceptibility. The package is inspired by work published in Valente, et al., (2015) DOI:10.1016/j.socscimed.2015.10.001; Valente (1995) ISBN:9781881303213, Myers (2000) DOI:10.1086/303110, Iyengar and others (2011) DOI:10.1287/mksc.1100.0566, Burt (1987) DOI:10.1086/228667; among others.

__Acknowledgements__: netdiffuseR was created with the support of grant R01
CA157577 from the National Cancer Institute/National Institutes of Health.